import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".vercel/**",
    "out/**",
    "build/**",
    "tmp/**",
    "next-env.d.ts",
    // Generated by fumadocs-mdx from source.config.ts.
    ".source/**",
    // Generated by windmill/generate-flows.mts from the native runtime.
    "windmill/f/**",
  ]),
  {
    files: [
      "lib/**/*.{ts,tsx}",
      "services/**/*.{ts,tsx}",
      "features/**/server/**/*.{ts,tsx}",
      "windmill/runtime/**/*.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/app/**", "@/components/**", "@/features/*/ui/**"],
              message:
                "Server and application modules cannot depend on route or UI modules. Move the shared contract into the owning feature domain.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["features/**/domain/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@/app/**",
                "@/components/**",
                "@/features/*/server/**",
                "@/features/*/ui/**",
              ],
              message:
                "Feature domain modules must remain independent from routes, UI, and server adapters.",
            },
          ],
        },
      ],
    },
  },
])

export default eslintConfig
