import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  // Only the Appwrite adapter and the provisioning script talk to Appwrite;
  // feature code goes through `@/lib/data` repositories.
  {
    files: ["**/*.{ts,tsx,mts,mjs,js}"],
    ignores: ["lib/data/appwrite/**", "scripts/appwrite-provision.mjs"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "node-appwrite", message: "Use the repositories from @/lib/data." },
            { name: "node-appwrite/file", message: "Use the repositories from @/lib/data." },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    ".vercel/**",
    "tmp/**",
    "next-env.d.ts",
    // Generated by fumadocs-mdx from source.config.ts.
    ".source/**",
  ]),
])

export default eslintConfig
