export const LUMENCLIP_MCP_TOOLS = [
  { name: "lumenclip_automations_list", category: "automations" },
  { name: "lumenclip_automation_templates_list", category: "automations" },
  { name: "lumenclip_automation_create", category: "automations" },
  { name: "lumenclip_automation_get", category: "automations" },
  { name: "lumenclip_automation_schema_update", category: "automations" },
  {
    name: "lumenclip_automation_formatting_update",
    category: "automations",
  },
  {
    name: "lumenclip_automation_text_item_update",
    category: "automations",
  },
  { name: "lumenclip_automation_delete", category: "automations" },
  { name: "lumenclip_automation_hooks_get", category: "automations" },
  { name: "lumenclip_automation_hooks_update", category: "automations" },
  { name: "lumenclip_automation_hook_upsert", category: "automations" },
  {
    name: "lumenclip_automation_hook_set_enabled",
    category: "automations",
  },
  { name: "lumenclip_automation_hook_delete", category: "automations" },
  { name: "lumenclip_hook_performance", category: "analytics" },
  { name: "lumenclip_run_plan_get", category: "automations" },
  { name: "lumenclip_automation_run", category: "automations" },
  { name: "lumenclip_schedule_get", category: "scheduling" },
  { name: "lumenclip_slideshow_generate", category: "slideshows" },
  { name: "lumenclip_ugc_estimate", category: "videos" },
  { name: "lumenclip_ugc_generate", category: "videos" },
  { name: "lumenclip_automation_update", category: "automations" },
  { name: "lumenclip_collections_list", category: "collections" },
  { name: "lumenclip_product_collection_get", category: "collections" },
  { name: "lumenclip_assets_list", category: "collections" },
  { name: "lumenclip_variable_get", category: "collections" },
  { name: "lumenclip_variable_save", category: "collections" },
  { name: "lumenclip_variable_delete", category: "collections" },
  { name: "lumenclip_collection_save", category: "collections" },
  { name: "lumenclip_collection_add_assets", category: "collections" },
  { name: "lumenclip_collection_delete", category: "collections" },
  { name: "lumenclip_outputs_list", category: "outputs" },
  { name: "lumenclip_output_delete", category: "outputs" },
  { name: "lumenclip_operations_list", category: "outputs" },
  { name: "lumenclip_operation_get", category: "outputs" },
  { name: "lumenclip_accounts_list", category: "publishing" },
  { name: "lumenclip_workspace_members_list", category: "publishing" },
  { name: "lumenclip_output_publish", category: "publishing" },
  { name: "lumenclip_output_mark_published", category: "publishing" },
  { name: "lumenclip_analytics_report", category: "analytics" },
  { name: "lumenclip_tiktok_import_start", category: "publishing" },
  { name: "lumenclip_tiktok_import_preview", category: "publishing" },
  { name: "lumenclip_tiktok_publications_link", category: "publishing" },
  {
    name: "lumenclip_tiktok_studio_analytics_import_start",
    category: "analytics",
  },
  {
    name: "lumenclip_tiktok_studio_analytics_report",
    category: "analytics",
  },
  {
    name: "lumenclip_tiktok_studio_analytics_batch_start",
    category: "analytics",
  },
] as const

export const LUMENCLIP_MCP_TOOL_NAMES = LUMENCLIP_MCP_TOOLS.map(
  (tool) => tool.name
)
