#!/usr/bin/env bash
# Cloud Agent start phase for LumenClip.
#
# Brings up the local Railway-compatible services every time the environment
# boots: PostgreSQL and an S3-compatible MinIO bucket. It writes the git-ignored
# local .env, applies checked-in migrations, and returns. It is idempotent and
# safe to re-run. The Next.js dev server itself runs as a visible terminal (see
# .cursor/environment.json), not here.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

PG_USER=lumenclip
PG_PASSWORD=lumenclip
PG_DB=lumenclip
PG_DSN="postgres://${PG_USER}:${PG_PASSWORD}@127.0.0.1:5432/${PG_DB}"

MINIO_DATA="${HOME}/.lumenclip/minio-data"
MINIO_USER=lumenclip
MINIO_PASSWORD=lumenclip-secret
BUCKET=lumenclip-assets

echo "[start] starting PostgreSQL cluster"
sudo pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

echo "[start] ensuring role and database"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PG_USER}') THEN
    CREATE ROLE ${PG_USER} LOGIN PASSWORD '${PG_PASSWORD}' SUPERUSER;
  END IF;
END \$\$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${PG_DB}'" | grep -q 1; then
  sudo -u postgres createdb -O "${PG_USER}" "${PG_DB}"
fi

echo "[start] starting MinIO (S3-compatible bucket)"
mkdir -p "${MINIO_DATA}"
if ! curl -fsS http://127.0.0.1:9000/minio/health/live >/dev/null 2>&1; then
  MINIO_ROOT_USER="${MINIO_USER}" MINIO_ROOT_PASSWORD="${MINIO_PASSWORD}" \
    nohup minio server "${MINIO_DATA}" --address :9000 --console-address :9001 \
    >/tmp/minio.log 2>&1 &
  for _ in $(seq 1 30); do
    if curl -fsS http://127.0.0.1:9000/minio/health/live >/dev/null 2>&1; then break; fi
    sleep 1
  done
fi
mc alias set localminio http://127.0.0.1:9000 "${MINIO_USER}" "${MINIO_PASSWORD}" >/dev/null 2>&1 || true
mc mb --ignore-existing localminio/"${BUCKET}" >/dev/null 2>&1 || true

echo "[start] writing local .env (git-ignored)"
# Local infrastructure only. Provider/Clerk secrets belong in the Secrets panel;
# real environment variables take precedence over these values, and Clerk runs
# in keyless dev mode when no publishable key is provided.
cat > .env <<ENV
# Auto-generated by .cursor/start.sh for local Cloud Agent development.
LUMENCLIP_DATA_BACKEND=railway
LUMENCLIP_ASSET_BACKEND=railway
DATABASE_URL=${PG_DSN}
LUMENCLIP_TEST_DATABASE_URL=${PG_DSN}
POSTGRES_POOL_SIZE=10
RAILWAY_BUCKET_NAME=${BUCKET}
RAILWAY_BUCKET_ENDPOINT=http://127.0.0.1:9000
RAILWAY_BUCKET_ACCESS_KEY_ID=${MINIO_USER}
RAILWAY_BUCKET_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
RAILWAY_BUCKET_REGION=auto
AWS_S3_URL_STYLE=path
POST_REPOSITORY_READ_MODE=legacy
POST_REPOSITORY_WRITE_MODE=legacy
ENABLE_INTERNAL_TOOLS=false
ENABLE_LOCAL_AUTOMATION_WORKER=false
ENV

echo "[start] applying database migrations"
DATABASE_URL="${PG_DSN}" pnpm railway:db:migrate

echo "[start] ready"
