/**
 * Experiment orchestrator: generate posts across the eval matrix, judge each,
 * write a JSON + markdown report, print the gate verdict.
 *
 * Codex: do not edit this file. Run it with a label after each presets change:
 *   node scripts/linkedin-lab/run.mjs --label v2-fold-first
 * Optional: --model <openrouter-id> (default anthropic/claude-sonnet-5)
 *
 * The eval matrix is FIXED (3 niches x 4 archetypes). Keep these archetype and
 * hook-style ids present in presets.mjs when refactoring:
 *   how_to_without+without_obstacle, struggles_advice+worried_problem,
 *   harsh_truth+harsh_truth, process_breakdown+steal_this
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import path from "node:path"
import { linkedInArchetypes, hookStyles, voicePresets, PRESET_VERSION } from "./presets.mjs"
import { deriveBrief, generatePost } from "./generate.mjs"
import { judgePost, evaluateGate, JUDGE_MODEL, QUALITY_GATE } from "./judge.mjs"

const ROOT = process.cwd()
try { process.loadEnvFile(path.join(ROOT, ".env")) } catch { /* env may already be set */ }
const apiKey = process.env.OPENROUTER_API_KEY
if (!apiKey) { console.error("OPENROUTER_API_KEY is not set"); process.exit(1) }

const args = process.argv.slice(2)
let label = ""
let model = "anthropic/claude-sonnet-5"
for (let i = 0; i < args.length; i += 1) {
  if (args[i] === "--label") label = args[++i]
  else if (args[i] === "--model") model = args[++i]
}
if (!label) { console.error("Usage: node scripts/linkedin-lab/run.mjs --label <iteration-label> [--model <id>]"); process.exit(1) }

const NICHES = [
  "AI content automation for solo marketers and one-person brands",
  "freelance web design for local service businesses",
  "career coaching for mid-level software engineers who feel stuck",
]

const MATRIX = [
  { archetypeId: "how_to_without", hookStyleId: "without_obstacle" },
  { archetypeId: "struggles_advice", hookStyleId: "worried_problem" },
  { archetypeId: "harsh_truth", hookStyleId: "harsh_truth" },
  { archetypeId: "process_breakdown", hookStyleId: "steal_this" },
]

const labDir = path.join(ROOT, "scripts", "linkedin-lab")
const resultsDir = path.join(labDir, "results")
mkdirSync(resultsDir, { recursive: true })

function pick(list, id, what) {
  const item = list.find((x) => x.id === id)
  if (!item) { console.error(`${what} "${id}" is missing from presets.mjs — the eval matrix requires it`); process.exit(1) }
  return item
}

// Briefs are derived once per niche and cached so every iteration compares
// against the same strategy.
const briefsPath = path.join(resultsDir, "briefs.json")
const briefs = existsSync(briefsPath) ? JSON.parse(readFileSync(briefsPath, "utf8")) : {}
for (const niche of NICHES) {
  if (!briefs[niche]) {
    console.log(`Deriving brief: ${niche}`)
    briefs[niche] = await deriveBrief({ apiKey, model: "google/gemini-3.1-flash-lite", niche })
    writeFileSync(briefsPath, JSON.stringify(briefs, null, 2))
  }
}

const voice = voicePresets.find((v) => v.id === "educator") ?? voicePresets[0]
const jobs = []
for (const niche of NICHES) {
  for (const cell of MATRIX) {
    jobs.push({
      niche,
      plan: {
        archetype: pick(linkedInArchetypes, cell.archetypeId, "archetype"),
        hookStyle: pick(hookStyles, cell.hookStyleId, "hook style"),
        pillar: briefs[niche].pillars[jobs.length % briefs[niche].pillars.length] ?? briefs[niche].pillars[0],
      },
    })
  }
}

console.log(`Running ${jobs.length} generations (${model}) + judging (${JUDGE_MODEL}) — presets ${PRESET_VERSION}`)

async function runJob(job, index) {
  const started = Date.now()
  const generated = await generatePost({
    apiKey,
    model,
    niche: job.niche,
    brief: briefs[job.niche],
    plan: job.plan,
    voice,
  })
  const judged = await judgePost({
    apiKey,
    niche: job.niche,
    brief: briefs[job.niche],
    post: generated.post,
    archetypeLabel: job.plan.archetype.label,
  })
  console.log(`  [${index + 1}/${jobs.length}] ${job.plan.archetype.id} / ${job.niche.slice(0, 40)}… overall ${judged.overall} (${generated.violations.length} violations, ${Date.now() - started}ms)`)
  return {
    niche: job.niche,
    archetype: job.plan.archetype.id,
    hookStyle: job.plan.hookStyle.id,
    pillar: job.plan.pillar,
    post: generated.post,
    attempts: generated.attempts,
    violations: generated.violations,
    scores: judged.scores,
    overall: judged.overall,
  }
}

const results = []
const CONCURRENCY = 4
for (let i = 0; i < jobs.length; i += CONCURRENCY) {
  const chunk = await Promise.all(jobs.slice(i, i + CONCURRENCY).map((job, offset) => runJob(job, i + offset)))
  results.push(...chunk)
}

const gate = evaluateGate(results)
const report = {
  label,
  presetVersion: PRESET_VERSION,
  model,
  judgeModel: JUDGE_MODEL,
  createdAt: new Date().toISOString(),
  gate,
  qualityGate: QUALITY_GATE,
  results,
}
const jsonPath = path.join(resultsDir, `${label}.json`)
writeFileSync(jsonPath, JSON.stringify(report, null, 2))

const md = [
  `# LinkedIn lab — ${label}`,
  ``,
  `presets: ${PRESET_VERSION} · generator: ${model} · judge: ${JUDGE_MODEL} · ${report.createdAt}`,
  ``,
  `## Gate: ${gate.passed ? "PASSED ✅" : "FAILED ❌"} — mean ${gate.mean} (need ≥ ${QUALITY_GATE.meanOverall}), min ${gate.min} (need ≥ ${QUALITY_GATE.minOverall}), violations ${gate.violations} (need ${QUALITY_GATE.maxViolations})`,
  ``,
  `| # | niche | archetype | overall | weakest | violations |`,
  `|---|---|---|---|---|---|`,
  ...results.map((r, i) => `| ${i + 1} | ${r.niche.slice(0, 38)} | ${r.archetype} | ${r.overall} | ${r.scores.weakestDimension} | ${r.violations.length} |`),
  ``,
  ...results.flatMap((r, i) => [
    `## Post ${i + 1} — ${r.archetype} · ${r.niche}`,
    ``,
    `overall **${r.overall}** · ${Object.entries(r.scores).filter(([k, v]) => typeof v === "number").map(([k, v]) => `${k} ${v}`).join(" · ")}`,
    ``,
    `top fix: ${r.scores.topFix}`,
    r.violations.length ? `violations: ${r.violations.join("; ")}` : ``,
    ``,
    "```",
    r.post,
    "```",
    ``,
  ]),
].join("\n")
const mdPath = path.join(resultsDir, `${label}.md`)
writeFileSync(mdPath, md)

console.log(`\nGate ${gate.passed ? "PASSED" : "FAILED"}: mean ${gate.mean}, min ${gate.min}, violations ${gate.violations}`)
console.log(`Report: ${mdPath}`)
