/**
 * Regenerates the MCP reference from the live tool registrations:
 * - `mcp/README.md` callable-tool list (between the generated markers)
 * - `mcp/tool-index.md` (every tool's category, description and input schema)
 *
 * `pnpm mcp:docs` writes; `pnpm mcp:docs:check` fails when either is stale.
 */
import fs from "node:fs"
import path from "node:path"

import { Client } from "@modelcontextprotocol/sdk/client/index.js"
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js"

import { createMemoryRepositories } from "@/lib/data"
import { createLumenClipMcpServer } from "@/lib/mcp/lumenclip-server"
import { LUMENCLIP_MCP_TOOL_CATEGORIES, LUMENCLIP_MCP_TOOLS } from "@/lib/mcp/tool-registry"
import { NotConfiguredPublisher } from "@/lib/publishing/publisher"

const start = "<!-- BEGIN:callable-tools -->"
const end = "<!-- END:callable-tools -->"
const check = process.argv.includes("--check")
const root = path.join(process.cwd(), "mcp")
const readmePath = path.join(root, "README.md")
const indexPath = path.join(root, "tool-index.md")

type JsonSchema = {
  type?: string | string[]
  description?: string
  properties?: Record<string, JsonSchema>
  required?: string[]
  enum?: unknown[]
  const?: unknown
  items?: JsonSchema
  default?: unknown
  anyOf?: JsonSchema[]
}

function typeLabel(schema: JsonSchema): string {
  if (schema.const !== undefined) return `\`${JSON.stringify(schema.const)}\``
  if (schema.enum) return schema.enum.map((v) => `\`${JSON.stringify(v)}\``).join(" \\| ")
  if (schema.anyOf) return schema.anyOf.map(typeLabel).join(" \\| ")
  if (schema.type === "array") return `${schema.items ? typeLabel(schema.items) : "any"}[]`
  if (Array.isArray(schema.type)) return schema.type.join(" \\| ")
  return schema.type ?? "any"
}

function inputTable(schema: JsonSchema): string {
  const properties = Object.entries(schema.properties ?? {})
  if (!properties.length) return "_No input._"
  const required = new Set(schema.required ?? [])
  const rows = properties.map(([name, prop]) => {
    const notes = [prop.description ?? "", prop.default !== undefined ? `Default \`${JSON.stringify(prop.default)}\`.` : ""]
      .filter(Boolean)
      .join(" ")
      .replace(/\|/g, "\\|")
      .replace(/\n/g, " ")
    return `| \`${name}\` | ${typeLabel(prop)} | ${required.has(name) ? "yes" : "no"} | ${notes} |`
  })
  return ["| Field | Type | Required | Notes |", "| --- | --- | --- | --- |", ...rows].join("\n")
}

async function main() {
  const repos = createMemoryRepositories()
  const server = createLumenClipMcpServer("docs", {
    repositories: () => repos,
    renderSpec: async () => ({ slides: [], warnings: [] }),
    publisher: () => new NotConfiguredPublisher(),
    apiBaseUrl: () => "/api/v1",
  })
  const client = new Client({ name: "mcp-docs", version: "1.0.0" })
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair()
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)])
  const { tools } = await client.listTools()
  await client.close()
  await server.close()
  const byName = new Map(tools.map((tool) => [tool.name, tool]))

  const sections: string[] = [
    "# MCP tool index",
    "",
    "<!-- Generated by `pnpm mcp:docs` from lib/mcp. Do not edit by hand. -->",
    "",
    "| Tool | Category | Title |",
    "| --- | --- | --- |",
    ...LUMENCLIP_MCP_TOOLS.map(
      (t) => `| [\`${t.name}\`](#${t.name}) | ${t.category} | ${byName.get(t.name)?.title ?? ""} |`
    ),
  ]
  for (const category of LUMENCLIP_MCP_TOOL_CATEGORIES) {
    sections.push("", `## ${category[0].toUpperCase()}${category.slice(1)}`)
    for (const entry of LUMENCLIP_MCP_TOOLS.filter((t) => t.category === category)) {
      const tool = byName.get(entry.name)
      if (!tool) throw new Error(`Tool ${entry.name} is in the registry but not registered`)
      sections.push(
        "",
        `### ${entry.name}`,
        "",
        tool.description ?? "",
        "",
        inputTable(tool.inputSchema as JsonSchema)
      )
    }
  }
  const index = sections.join("\n") + "\n"

  const readme = fs.readFileSync(readmePath, "utf8")
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`)
  if (!pattern.test(readme)) throw new Error(`Missing generated tool markers in ${readmePath}`)
  const nextReadme = readme.replace(
    pattern,
    [start, ...LUMENCLIP_MCP_TOOLS.map((t) => `- \`${t.name}\` (${t.category})`), end].join("\n")
  )

  const currentIndex = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, "utf8") : ""
  if (check) {
    if (nextReadme !== readme || index !== currentIndex) {
      throw new Error("mcp/README.md or mcp/tool-index.md is stale; run pnpm mcp:docs")
    }
    return
  }
  if (nextReadme !== readme) fs.writeFileSync(readmePath, nextReadme)
  if (index !== currentIndex) fs.writeFileSync(indexPath, index)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
