"use client"

import { useEffect, useState } from "react"
import { IconChartBar, IconReload } from "@tabler/icons-react"

import { fetchJsonWithTimeout, getApiErrorMessage } from "@/lib/client-api"
import type { HookAnalyticsRow } from "@/lib/hook-publications"
import type { Automation } from "@/lib/realfarm-data"

import { SettingsPage } from "./settings-layout"

type HookAnalyticsPayload = {
  automationId: string
  rows: HookAnalyticsRow[]
}

export function HookAnalyticsPanel({ automation }: { automation: Automation }) {
  const [rows, setRows] = useState<HookAnalyticsRow[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [loadedAutomationId, setLoadedAutomationId] = useState("")
  const [reloadKey, setReloadKey] = useState(0)
  const isLoading = loading || loadedAutomationId !== automation.id
  const visibleRows = loadedAutomationId === automation.id ? rows : []

  useEffect(() => {
    let active = true
    void fetchJsonWithTimeout<HookAnalyticsPayload>(
      `/api/automations/${encodeURIComponent(automation.id)}/hook-analytics`,
      { toastOnError: false }
    )
      .then((payload) => {
        if (active) {
          setRows(payload.rows ?? [])
          setError("")
          setLoadedAutomationId(automation.id)
        }
      })
      .catch((cause) => {
        if (active) {
          setError(
            getApiErrorMessage(cause, "Hook analytics could not be loaded.")
          )
          setLoadedAutomationId(automation.id)
        }
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [automation.id, reloadKey])

  return (
    <SettingsPage
      title="Hook analytics"
      description={`Performance from published posts generated by ${automation.name}. Drafts and scheduled posts are excluded.`}
      action={
        <button
          type="button"
          className="mr-10 inline-flex h-9 items-center gap-2 rounded-[7px] border border-app-panel-border bg-app-surface px-3 text-[13px] font-semibold text-app-text shadow-sm hover:bg-app-surface-subtle disabled:opacity-50"
          disabled={isLoading}
          onClick={() => {
            setLoading(true)
            setError("")
            setReloadKey((value) => value + 1)
          }}
        >
          <IconReload
            className={isLoading ? "size-4 animate-spin" : "size-4"}
          />
          Refresh
        </button>
      }
    >
      <div className="pt-6">
        {isLoading ? (
          <AnalyticsMessage title="Loading hook performance…" />
        ) : error ? (
          <AnalyticsMessage title="Hook analytics unavailable" detail={error} />
        ) : visibleRows.length === 0 ? (
          <AnalyticsMessage
            title="No used hooks yet"
            detail="A hook appears here after PostFast confirms it as published, or after you mark an output as published and link its public post."
          />
        ) : (
          <div className="overflow-x-auto rounded-[10px] border border-app-panel-border bg-app-surface shadow-sm">
            <table className="w-full min-w-[980px] border-collapse text-left">
              <thead className="bg-app-surface-subtle text-[11px] tracking-[0.06em] text-app-text-faint uppercase">
                <tr>
                  <Header>Hook</Header>
                  <Header align="right">Posts</Header>
                  <Header>Last published</Header>
                  <Header>Platforms</Header>
                  <Header align="right">Views</Header>
                  <Header align="right">Likes</Header>
                  <Header align="right">Comments</Header>
                  <Header align="right">Shares</Header>
                  <Header align="right">Saves</Header>
                  <Header align="right">Engagement</Header>
                </tr>
              </thead>
              <tbody>
                {visibleRows.map((row) => (
                  <tr
                    key={row.hookId}
                    className="border-t border-app-panel-border text-[13px] font-medium text-app-text"
                  >
                    <td className="max-w-[360px] px-4 py-4">
                      <div className="line-clamp-2 leading-5 font-semibold">
                        {row.text}
                      </div>
                      {!row.enabled ? (
                        <span className="mt-1 inline-flex rounded-full bg-[#efeee9] px-2 py-0.5 text-[10px] font-bold tracking-[0.04em] text-app-text-faint uppercase">
                          Disabled
                        </span>
                      ) : null}
                    </td>
                    <MetricCell value={row.publishedPosts} />
                    <td className="px-4 py-4 whitespace-nowrap text-app-text-soft">
                      {formatDate(row.lastPublishedAt)}
                    </td>
                    <td className="px-4 py-4 text-app-text-soft capitalize">
                      {row.providers.join(", ")}
                    </td>
                    <MetricCell value={row.metrics.views} />
                    <MetricCell value={row.metrics.likes} />
                    <MetricCell value={row.metrics.comments} />
                    <MetricCell value={row.metrics.shares} />
                    <MetricCell value={row.metrics.saves} />
                    <td className="px-4 py-4 text-right whitespace-nowrap tabular-nums">
                      {row.metrics.engagementRate === undefined
                        ? "—"
                        : `${row.metrics.engagementRate.toFixed(2)}%`}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </SettingsPage>
  )
}

function Header({
  children,
  align = "left",
}: {
  children: React.ReactNode
  align?: "left" | "right"
}) {
  return (
    <th
      className={`px-4 py-3 font-bold ${align === "right" ? "text-right" : ""}`}
    >
      {children}
    </th>
  )
}

function MetricCell({ value }: { value?: number }) {
  return (
    <td className="px-4 py-4 text-right whitespace-nowrap tabular-nums">
      {value === undefined ? "—" : compactNumber(value)}
    </td>
  )
}

function AnalyticsMessage({
  title,
  detail,
}: {
  title: string
  detail?: string
}) {
  return (
    <div className="flex min-h-64 flex-col items-center justify-center rounded-[10px] border border-dashed border-app-panel-border bg-app-surface-subtle px-8 text-center">
      <span className="mb-3 grid size-10 place-items-center rounded-full bg-[#eee9fb] text-app-action">
        <IconChartBar className="size-5" />
      </span>
      <div className="text-[16px] font-semibold text-app-text">{title}</div>
      {detail ? (
        <p className="mt-2 max-w-lg text-[13px] leading-5 font-medium text-app-muted-text">
          {detail}
        </p>
      ) : null}
    </div>
  )
}

function compactNumber(value: number) {
  return new Intl.NumberFormat("en", {
    notation: value >= 1_000 ? "compact" : "standard",
    maximumFractionDigits: 1,
  }).format(value)
}

function formatDate(value: string) {
  const date = new Date(value)
  return Number.isNaN(date.getTime())
    ? "—"
    : new Intl.DateTimeFormat("en", {
        day: "numeric",
        month: "short",
        year: "numeric",
      }).format(date)
}
